#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get update -y

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update -y

apt-get install haproxy=2.0.\*

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 182-web-01 34.75.214.109 
    server 182-web-02 35.190.185.74
    option httpchk
" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
