#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

sudo echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 182-web-01 34.75.214.109 check
    server 182-web-02 35.190.185.74 check
    option httpchk
    option httpclose
" >> sudo /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
